kind: List
apiVersion: v1

items:

  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: "filter"
    labels:
      application: "filter"
    spec:
      dockerImageRepository: "filter"
      tags:
      - name: latest
      lookupPolicy:
        local: true

  - apiVersion: v1
    kind: BuildConfig
    metadata:
      name: "filter"
    labels:
      application: "filter"
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: "filter:latest"
      source:
        git:
          uri: "https://github.com/rebeccaSimmonds19/transaction_limit"
        type: Git
          github:
          secret: "secret101"
      strategy:
        sourceStrategy:
          env:
          - name: APP_FILE
            value: "transaction_limit-1.0-SNAPSHOT.jar"
          forcePull: false
          from:
            kind: DockerImage
            name: radanalyticsio/radanalytics-java-spark:v0.4.6
        type: Source
      triggers:
      - imageChange: {}
        type: ImageChange
        type: ConfigChange
      - github:
          secret: secret101
        type: GitHub
        
  - apiVersion: v1
    kind: Template
    metadata:
      name: filter
    parameters:
    - description: List of additional spark options to pass to spark-submit (for exmaple --conf property=value --conf property=value). Note, --master and --class are set by the launcher and should not be set here
      name: SPARK_OPTIONS
    - description: The name of the spark cluster to run against. The cluster will be created if it does not exist, and a random cluster name will be chosen if this value is left blank.
      name: OSHINKO_CLUSTER_NAME
    objects:

      - kind: Job
        apiVersion: batch/v1
        metadata:
          name: "filter"
        spec:
          parallelism: 1
          completions: 1
          template:
            metadata:
              name: ${JOB_NAME}
            spec:
              containers:
                - name: filter
                  image: "filter:latest"
                  env:
                  - name: POD_NAME
                    valueFrom:
                      fieldRef:
                        fieldPath: metadata.name
                  volumeMounts:
                  - mountPath: /etc/podinfo
                    name: podinfo
                    readOnly: false
              restartPolicy: Never
              serviceAccount: oshinko
              volumes:
              - downwardAPI:
                  items:
                  - fieldRef:
                      fieldPath: metadata.labels
                    path: labels
                name: podinfo
