kind: List
apiVersion: v1

items:

  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: "filter"
    labels:
      application: "filter"
      spec:
        dockerImageRepository: "filter"
        tags:
        - name: latest
          lookupPolicy:
            local: true

  - apiVersion: v1
    kind: BuildConfig
    metadata:
      name: "filter"
    labels:
      application: "filter"
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: "filter:latest"
      source:
        git:
          uri: "https://github.com/rebeccaSimmonds19/transaction_limit"
        type: Git
      strategy:
        sourceStrategy:
          env:
          - name: APP_FILE
            value: "transaction_limit-1.0-SNAPSHOT.jar"
          forcePull: false
          from:
            kind: DockerImage
            name: radanalyticsio/radanalytics-java-spark
        type: Source
      triggers:
      - imageChange: {}
        type: ImageChange
        type: ConfigChange

  - apiVersion: v1
    kind: Template
    metadata:
      name: filter
    parameters:
    - description: List of additional spark options to pass to spark-submit (for exmaple --conf property=value --conf property=value). Note, --master and --class are set by the launcher and should not be set here
      name: SPARK_OPTIONS
    objects:

      - kind: Job
        apiVersion: batch/v1
        metadata:
          name: "filter"
        spec:
          parallelism: 1
          completions: 1
          template:
            metadata:
              name: ${JOB_NAME}
            spec:
              containers:
                - name: filter
                  image: "172.30.1.1:5000/project/filter"
                  env:
                  - name: POD_NAME
                    valueFrom:
                      fieldRef:
                        fieldPath: metadata.name
                  volumeMounts:
                  - mountPath: /etc/podinfo
                    name: podinfo
                    readOnly: false
              restartPolicy: Never
              serviceAccount: oshinko
              volumes:
              - downwardAPI:
                  items:
                  - fieldRef:
                      fieldPath: metadata.labels
                    path: labels
                name: podinfo
